apiVersion: batch/v1beta1
kind: CronJob

metadata:
  name: dataset-harvest-aggregator

spec:
  schedule: "20 * * * *"
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: regsecret
          containers:
            - name: aggregator
              image: container-registry.oslo.kommune.no/dataset-harvest-aggregator:latest
              command:
                - /bin/sh
              args:
                - -c
                - mkdir -p /data/dataset/20_aggregations && mkdir -p /data/dataset/30_result && cat /data/dataset/10_raw/dataplatform-datasets.json | python /app/aggregator.py
              env:
                - name: AGGREGATIONS_PATH
                  value: /data/dataset/20_aggregations
                - name: RESULT_PATH
                  value: /data/dataset/30_result
                - name: TMP_PATH
                  value: /data/dataset/tmp
              volumeMounts:
                - name: harvest-output
                  mountPath: /data
                - name: temp
                  mountPath: /data/dataset/tmp
          volumes:
            - name: harvest-output
              persistentVolumeClaim:
                claimName: harvest-output
            - name: temp
              emptyDir: {}
