apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        ingress: enabled
        app: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
        - image: container-registry.oslo.kommune.no/latest-provider:{{ .Values.version }}
          imagePullPolicy: Always
          name: "{{ .Chart.Name }}"
          env:
            - name: PROVIDER_DATA_DIR
              value: /data
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /data
              name: harvest-output
            - mountPath: /tmp
              name: temp
      volumes:
        - name: harvest-output
          persistentVolumeClaim:
            claimName: harvest-output
        - name: temp
          emptydir: {}
